dinner_outcomes = {
    "You eat dinner with Jay-Z. His business acumen is as sharp as his fashion sense, and you find yourself learning a lot about the music industry. You make $10,000.": 10000,
    "You eat dinner with Jay-Z. He tells you about a time that the Roc was in the building, back in the early 2000s.": 0,
    "You go to a Chinese restaurant with Jay-Z. On the way there, he keeps telling you about something called the 'White Rice Challenge', but when you arrive the waitress serving you is confused by his request.": 0,
    "You go to a Chinese restaurant with Jay-Z. On the way there, he keeps telling you about something called the 'White Rice Challenge', but he chickens out at the last minute and pays you $10,000 to keep it quiet.": 10000,
    "You eat dinner with Jay-Z. You convince him to sign over the rights to Memphis Bleek's discography to you. You make $900.": 900,
    "You eat dinner with Jay-Z. He tries to claim that he was a ghostwriter on Nas's Ether, but you call him out on it and he stays silent for the rest of the meal.": 0,
    "You go to dinner with Jay-Z, but he pretends to not know who you are and spends the whole meal playing some kind of helicopter-themed gacha game on his phone.": 0,
    "You go to dinner with Jay-Z. Throughout the meal, a man that looks exactly like Jay-Z bangs on the window of the restaurant, begging to be let inside.": 0,
    "You go to dinner with Jay-Z, and he laughs at you for still using a knife and fork. He explains that they will soon become obsolete.": 0,
    "You go to dinner with Jay-Z and he gives you a signed Memphis Bleek poster. You sell it for $15.": 15,
    "You try to get dinner with Jay-Z, but he runs late due to an appointment at the helicopter dealership.": 0,
    "You go to lunch with Jay-Z. He seems to be confused and disoriented, and his shirt is on backwards.": 0,
    "Over dinner with Jay-Z, he tells you that he has written a Discord bot that has a command that allows users to get dinner with him. Then he give you $100.": 100,
    "You forgo the dinner and take the $50,000, using $45,000 to buy a solid gold CD copy of his 2008 album 'The Blueprint 3'.": 5000,
    "Over dinner, Jay-Z pitches you on the idea of becoming an investor in his Tidal streaming service. You lose $50,000.": -50000,
    "Over dinner, Jay-Z tells you that he is in an ongoing legal battle with Wikipedia over a line on his biography that suggests that the Roc wasn't actually in the building. He offers you $50,000 to go home and edit the article.": 50000,
    "You forgo the dinner and take the $50,000. Jay-Z reveals to you that if you had gone to dinner with him, the valuable insights into business you would have learned could have been worth more than $50,000.": 50000,
    "You forgo the dinner and take the $50,000, using $6,000 to hire a Jay-Z impersonator to follow you around and say 'Hov's in the building!' whenever you enter a room.": 44000,
    "You forgo the dinner and take the $50,000, using $6,000 to hire a Jay-Z impersonator who you then have dinner with.": 44000,
    "You forgo the dinner and take the $50,000, using $2,000 to buy a ticket to see Jay-Z perform at Madison Square Garden.": 48000,
    "You forgo the dinner and take the $50,000, using it to buy the original diamond that Kanye West threw into the sky during the recording of 'Diamonds from Sierra Leone'.": 0,
    "You forgo the dinner and take the $50,000, using $600 to buy a slice of toast on eBay that has a vaguely Jay-Z-shaped burn mark on it.": 49400,
    "You forgo the dinner and take the $50,000, using it to put on a production of the 1977 musical 'Annie', replacing the soundtrack with songs from the 1998 Jay-Z album 'Vol. 2... Hard Knock Life'. The show is a huge success and you make $100,000.": 100000,
    "You forgo the dinner and take the $50,000, using it to put on a production of the 1977 musical 'Annie', replacing the soundtrack with songs from the 1998 Jay-Z album 'Vol. 2... Hard Knock Life'. The show is a critical failure and ballooning costs lead to a massive loss.": -100000,
    "You forgo the dinner and take the $50,000, using it to make a series of shrewd investments. After a few years, your return is in excess of $51,000.": 51000,
    "You forgo the dinner and take the $50,000, using it to make a series of poor investments. After a few years, your original investment has been reduced to $49,000.": 49000,
    "Jay-Z flies into a rage because the gazpacho soup is too cold. You are unable to glean any useful information from the dinner.": 0,
    "Jay-Z burns the roof of his mouth on the gazpacho soup, explaining that because he expected it to be ice cold, the soup being room temperature was like a shock to his system.": 0,
    "Jay-z leans in conspiratorially and tells you that the eponymous 'town' referenced in his 2009 hit Run This Town is actually Portland, Maine. ": 0,
    "Jay-Z leans in conspiratorially and tells you that the eponymous 'town' referenced in his 2009 hit Run This Town was actually a metaphor for the music industry. You use this information to become a successful music executive, and you make $100,000.": 100000,
    "Jay-Z explains to you how to whip coke over a stove using a Pyrex jug.": 600000,
    "Jay-Z explains to you that the secret ingredient in his music is love.": 0,
    "Jay-Z explains that the famous clip of him nodding to a Timbaland beat was actually staged with a series of lifelike puppets.": 0,
    "Jay-Z explains that he has never actually sat courtside at a basketball game, and that all the famous footage of him doing so was achieved with a combination of green screen and CGI.": 0,
    "Jay-Z produces a piece of paper from his pocket with the equation 'Profit = Revenue - Costs' written on it, and explains that this is the key to his success.": 0,
    "Jay-Z reveals that he is actually a time-traveling frog who has been manipulating the music industry for centuries, and that his real name is Glarb.": 0,
    "Jay-Z narrowly defeats you in a rock-paper-scissors best of 7.": 0,
    "You narrowly defeat Jay-Z in a rock-paper-scissors best of 7. He gives you $10,000.": 10000,
    "You accidentally call Jay-Z 'Jay-G' and he is so offended that he cancels the dinner and leaves, leaving you with nothing but a $50,000 bill for the meal.": -50000,
    "You accidentally call Jay-Z 'Jay-G' and he finds it hilarious. He changes his name to Jay-G for the rest of the meal and gives you $10,000.": 10000,
    "You play the Jay-Z 'Monster' verse parody off your phone, and he does not find it funny. He leaves the dinner early, and you are left with a $50,000 bill for the meal.": -50000,
    "You play the Jay-Z 'Monster' verse parody off your phone, and he finds it hilarious. He laughs so hard that he accidentally chokes on his food and dies, leaving you with a $50,000 bill for the meal and a lifetime of guilt.": -50000,
    "You play the Jay-Z 'Monster' verse parody off your phone, and he reveals that he what you understood as the 'parody' was actually the original verse before Kanye demanded changes.": 0,
    "You stand up in the restaurant, point at him, and shout 'More like Gay-Z!' at the top of your lungs. He leaves in tears.": 0,
    "You stand up in the restaurant, point at him, and shout 'More like Gay-Z!' at the top of your lungs. The clip goes viral after being purchased by TMZ and you lose your job and become homeless due to your actions.": -50000,
    "You make a documentary about the dinner called 'My Dinner with Jay-Z', which becomes a cult classic and earns you $100,000 in royalties.": 100000,
    "You make a documentary about the dinner called 'My Dinner with Jay-Z', and the distributor of the 1981 film 'My Dinner with Andre' sues you for copyright infringement. You lose the lawsuit and are ordered to pay $50,000 in damages.": -50000,
    "You cancel the dinner at the last minute and decide to enter a Jay-Z lookalike contest instead. You come in second place, losing to Jay-Z. You win a $300 cash prize.": 300,
    "You cancel the dinner at the last minute and decide to enter a Jay-Z lookalike contest instead. You win first place, beating out Jay-Z himself, and win a $10,000 cash prize.": 10000,
    "You cancel the dinner at the last minute and decide to enter a Jay-Z lookalike contest instead. You win first place, beating out Jay-Z himself. The prize is a signed copy of his 2003 album 'The Black Album', which you sell for $50,000.": 50000,
}
